### ISSUE TITLE
This looks amazing

### ISSUE THREAD

**Issue by ganeshdevis** [Oldharlem/spree_channable#11]
I just wanted to wish you for this awesome gem but I don't know how to reach you. searched you in Spree official slack channel but you are not there.

I will try to test this gem and let you know if I could help on anyway.

**Comment by Oldharlem** [comment]
Thanks for your feedback! Repo has been stale for a few months but any arising issues will be resolved. 

Any help on testing the jobs (orders / returns) would be apreciated 🙏
